### ISSUE TITLE
Kebab-case file matching

### ISSUE THREAD

**Issue by FieryCod** [selaux/eslint-plugin-filenames#19]
Having problem with creating kebab-case matching regex.
This is how my regex looks like `[a-z]+-?[a-z]+?\.?(test)?\.?js`

These are my tests for regex:

> error-handler.test.js
> index.js
> jsonrefs-resolver.test.js                                                                              
> swagger.test.js
> tests.js
> indexCC.js
> indexCC_blabla.js

Error I am receiving:

```
Error: unknown escape sequence at line 10, column 49:
     ... tch-regex: [2, "[a-z]+-?[a-z]+?\.?(test)?\.?js", true]
                                         ^
Error
    at generateError (/home/fierycod/KNIT-homepage-back/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/home/fierycod/KNIT-homepage-back/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readDoubleQuotedScalar (/home/fierycod/KNIT-homepage-back/node_modules/js-yaml/lib/js-yaml/loader.js:618:9)
    at composeNode (/home/fierycod/KNIT-homepage-back/node_modules/js-yaml/lib/js-yaml/loader.js:1337:13)
    at readFlowCollection (/home/fierycod/KNIT-homepage-back/node_modules/js-yaml/lib/js-yaml/loader.js:707:5)
    at composeNode (/home/fierycod/KNIT-homepage-back/node_modules/js-yaml/lib/js-yaml/loader.js:1332:11)
    at readBlockMapping (/home/fierycod/KNIT-homepage-back/node_modules/js-yaml/lib/js-yaml/loader.js:1061:11)
    at composeNode (/home/fierycod/KNIT-homepage-back/node_modules/js-yaml/lib/js-yaml/loader.js:1331:12)
    at readBlockMapping (/home/fierycod/KNIT-homepage-back/node_modules/js-yaml/lib/js-yaml/loader.js:1061:11)
    at composeNode (/home/fierycod/KNIT-homepage-back/node_modules/js-yaml/lib/js-yaml/loader.js:1331:12)
```
The question is how to enable only `kebab-case` file naming?

**Comment by selaux** [comment]
My guess is you have to escape the backslash in the regex...

**Comment by selaux** [comment]
Any update? Otherwise I will close 😉 ...

**Comment by selaux** [comment]
Thx 🙂
